spring.application.name=BT4
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=13600

influx.url=http://localhost:8086/
influx.token=CBap0zc0WPeZmTgNzNBF5s8mdj1cHzbmw8_0cIEumo-MrLRsUblN1XwRmRDUx8FjfSm0MjDe_LsqK71aX9kREQ==
influx.org=java
influx.bucket=java

spring.datasource.url=jdbc:mysql://localhost:3306/book
spring.datasource.username=root
spring.datasource.password=tubeo1012
